DROP TABLE IF EXISTS tbl_students;
CREATE TABLE tbl_students (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  age BIGINT,
  address VARCHAR(250) NOT NULL
);